baseURL = "https://trouvaille0198.github.io/Notes"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "伤心肠粉的酱油碟子"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

enableGitInfo = true
# 设置自动更新修改时间
[frontmatter]
lastmod = [':git', 'lastmod', ':fileModTime', ':default']

[params]
# LoveIt 主题版本
version = "0.2.X"
[params.page]
[params.page.toc]
# 是否使用目录
enable = true
# 是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = true
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
# 默认展开显示的代码行数
maxShownLines = 40
# 文章页面的分享信息设置

[params.page.math]
enable = true
# 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# 默认行内定界符是 $ ... $ 和 \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true

# 搜索配置
[params.search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
# 最大结果数目
maxResultLength = 10
# 结果内容片段长度
snippetLength = 50
# 搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
# 是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[params.search.algolia]
appID = ""
index = ""
searchKey = ""

# 页面头部导航栏配置
[params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
# LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
logo = ""
# 标题名称
name = "伤心肠粉"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
typeit = false

[params.footer]
enable = true
# 自定义内容 (支持 HTML 格式)
custom = '酒困路长惟欲睡，日高人渴漫思茶'
#  是否显示 Hugo 和主题信息
hugo = false
#  是否显示版权信息
copyright = true
#  是否显示作者
author = false
# 网站创立年份
since = 2022

# 主页配置
[params.home]
#  RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# 主页显示头像的 URL
avatarURL = "https://markdown-1303167219.cos.ap-shanghai.myqcloud.com/57000045"
#  主页显示的网站标题 (支持 HTML 格式)
title = "伤心肠粉的酱油碟子"
# 主页显示的网站副标题
subtitle = "这个打字机效果还蛮帅的"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
#  免责声明 (支持 HTML 格式)
disclaimer = ""
# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 6
# 被 params.page 中的 hiddenFromHomePage 替代
# 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
defaultHiddenFromHomePage = false

# 作者的社交信息设置
[params.social]
Email = "melonsoul@qq.com"
GitHub = "Trouvaille0198"
Steam = "111004917"

[menu]
[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
name = "文章"
post = ""
url = "posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1
[[menu.main]]
identifier = "tags"
name = "标签"
post = ""
pre = ""
title = ""
url = "tags/"
weight = 2
[[menu.main]]
identifier = "categories"
name = "分类"
post = ""
pre = ""
title = ""
url = "categories/"
weight = 3

# Hugo 解析文档的配置
[markup]
# 语法高亮设置
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false 是必要的设置
# (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
# Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# 是否在文档中直接使用 HTML 标签
unsafe = true
# 目录设置
[markup.tableOfContents]
endLevel = 6
startLevel = 2
